//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew
    {
        public Crew()
        {
            this.Whitelists = new HashSet<Whitelist>();
        }
    
        public long barcode { get; set; }
        public string name { get; set; }
        public System.DateTime tanggal_daftar { get; set; }
        public string status { get; set; }
        public string airport { get; set; }
        public string company_airways { get; set; }
    
        public virtual ICollection<Whitelist> Whitelists { get; set; }
    }
}
